'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Administrador_tb
    Public Property idAdministrador As Integer
    Public Property NomeCompleto As String
    Public Property NomeUsuario As String
    Public Property SenhaUsuario As String
    Public Property DataRegistro As Nullable(Of Date)

End Class
