'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cadeira_tb
    Public Property idCadeira As Integer
    Public Property Nome_Cadeira As String
    Public Property Credito_Cadeira As Integer
    Public Property Ano As Integer
    Public Property Semestre As Integer
    Public Property idCurso As Integer
    Public Property TipoCadeira As String

    Public Overridable Property Cusos_tb As Cusos_tb
    Public Overridable Property Criar_Horario_tb As ICollection(Of Criar_Horario_tb) = New HashSet(Of Criar_Horario_tb)

End Class
