'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Criar_Horario_tb
    Public Property idHorario As Integer
    Public Property idDia As Nullable(Of Integer)
    Public Property idDocente As Nullable(Of Integer)
    Public Property idCadeira As Nullable(Of Integer)
    Public Property idHoras As Nullable(Of Integer)
    Public Property idFaculdade As Nullable(Of Integer)
    Public Property idHorarioPorSemestre As Nullable(Of Integer)

    Public Overridable Property Cadeira_tb As Cadeira_tb
    Public Overridable Property Docente_tb As Docente_tb
    Public Overridable Property Faculdade_tb As Faculdade_tb
    Public Overridable Property Semana_tb As Semana_tb
    Public Overridable Property Horario_tb As Horario_tb

End Class
