'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cusos_tb
    Public Property idCurso As Integer
    Public Property Nome_Curso As String
    Public Property Duracao_Curso As Integer

    Public Overridable Property Cadeira_tb As ICollection(Of Cadeira_tb) = New HashSet(Of Cadeira_tb)

End Class
