'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Docente_tb
    Public Property idDocente As Integer
    Public Property Nome_Docente As String
    Public Property Formacao_Academica As String
    Public Property idDepartamento As Integer

    Public Overridable Property Criar_Horario_tb As ICollection(Of Criar_Horario_tb) = New HashSet(Of Criar_Horario_tb)
    Public Overridable Property Departamento_tb As Departamento_tb

End Class
