'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Faculdade_tb
    Public Property idFaculdade As Integer
    Public Property Nome_Universidade As String
    Public Property Nome_Extensao As String
    Public Property logotipo As Byte()

    Public Overridable Property Criar_Horario_tb As ICollection(Of Criar_Horario_tb) = New HashSet(Of Criar_Horario_tb)

End Class
