'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Horario_tb
    Public Property idHorarioPorSemana As Integer
    Public Property Ano As Nullable(Of Integer)
    Public Property Semestre As Nullable(Of Integer)
    Public Property idSala As Nullable(Of Integer)
    Public Property idPeriodo As Nullable(Of Integer)
    Public Property idCurso As Nullable(Of Integer)
    Public Property idAno As Nullable(Of Integer)

    Public Overridable Property Criar_Horario_tb As ICollection(Of Criar_Horario_tb) = New HashSet(Of Criar_Horario_tb)
    Public Overridable Property Periodo_tb As Periodo_tb
    Public Overridable Property Salas_tb As Salas_tb

End Class
