'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Horas_tb
    Public Property Horas As String
    Public Property idPeriodo As Nullable(Of Integer)
    Public Property idHoras As Integer

    Public Overridable Property Periodo_tb As Periodo_tb

End Class
