'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Licenca_tb
    Public Property idLicenca As Integer
    Public Property Dia As String
    Public Property Mes As String
    Public Property Ano As String
    Public Property Expiration As String
    Public Property ProductoKey As String
    Public Property FullName As String
    Public Property TypeLicenc As String

End Class
