'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Periodo_tb
    Public Property idPeriodo As Integer
    Public Property Nome_periodo As String

    Public Overridable Property Horario_tb As ICollection(Of Horario_tb) = New HashSet(Of Horario_tb)
    Public Overridable Property Horas_tb As ICollection(Of Horas_tb) = New HashSet(Of Horas_tb)

End Class
