'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class View_Horario
    Public Property idCriarHoriario As Integer
    Public Property Ano As Nullable(Of Integer)
    Public Property Semestre As Nullable(Of Integer)
    Public Property idSala As Nullable(Of Integer)
    Public Property idPeriodo As Nullable(Of Integer)
    Public Property idCurso As Nullable(Of Integer)
    Public Property idDia As Nullable(Of Integer)
    Public Property idDocente As Nullable(Of Integer)
    Public Property idCadeira As Nullable(Of Integer)
    Public Property idHoras As Nullable(Of Integer)
    Public Property idFaculdade As Nullable(Of Integer)
    Public Property Nome_Cadeira As String
    Public Property Nome_Docente As String
    Public Property Horas As String
    Public Property Nome_periodo As String
    Public Property Nome_Curso As String
    Public Property Dia As String
    Public Property Nome_Sala As String
    Public Property idHorarioPorSemestre As Nullable(Of Integer)
    Public Property idAno As Nullable(Of Integer)
    Public Property idHorarioPorSemana As Integer

End Class
