'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class View_ListaHorario
    Public Property Semestre As Nullable(Of Integer)
    Public Property Ano As Nullable(Of Integer)
    Public Property idSala As Integer
    Public Property Nome_Sala As String
    Public Property idPeriodo As Integer
    Public Property Nome_periodo As String
    Public Property idCurso As Integer
    Public Property Nome_Curso As String
    Public Property idAno As Nullable(Of Integer)
    Public Property idHorarioPorSemana As Integer

End Class
